var db = require('../config_db').db;
var TIPO_CENTRO = 0;

exports.findAll = function(req, res) {
    var deas = [
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
        {"Evento": "Solicitud", "Razón Social": 'Gimnasio Anabolic', "Fecha": '08-07-2017', "Hora": "21:09", "Usuario":"Juan"},
        {"Evento": "Devolución", "Razón Social": 'Facultad de Ingenieria UBA', "Fecha": '01-02-2015', "Hora": "15:09", "Usuario":"Felipe"},
        {"Evento": "Modificación", "Razón Social": 'Hospital Álvarez', "Fecha": '03-12-2017', "Hora": "16:09", "Usuario":"Adrián"},
        {"Evento": "Activación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "12:09", "Usuario":"Julián"},
        {"Evento": "Desactivación", "Razón Social": 'Hospital Churruca', "Fecha": '21-09-2009', "Hora": "14:09", "Usuario":"Tobias"},
    ]
    res.status(200).jsonp(deas);
};